[package]
name = "host-shared"
version.workspace = true
edition.workspace = true

[features]
test = [ "dep:env_logger" ]

[dependencies]
shared.workspace = true
log.workspace = true

num_cpus = "1.16"
env_logger = { version = "0.11.8", optional = true  }

