[package]
name = "testing-tests"
version.workspace = true
edition.workspace = true

[features]
default = ["test"]
test = []

[dependencies]
shared.workspace = true
testing = {path = ".."}

linkme.workspace = true
log.workspace = true
