[package]
name = "wasabi-test"
version = "0.1.0"
edition = "2021"

[features]
no-color = ["wasabi-kernel/no-color"]

[dependencies]
shared = { path = "../shared" }
testing = { path = "../testing" }
staticvec = { path = "../staticvec" }

bootloader_api = { version = "0.11.3", path = "../../bootloader/api" }
log.workspace = true
x86_64.workspace = true
linkme.workspace = true
itertools.workspace = true
uart_16550.workspace = true

[dependencies.wasabi-kernel]
path = "../wasabi-kernel"
features = ["test", "no-unicode-log"]
