[package]
name = "wasabi-test"
version.workspace = true
edition.workspace = true

[features]
no-color = ["wasabi-kernel/no-color"]

[dependencies]
shared = { path = "../shared" }
testing = { path = "../testing" }
staticvec = { path = "../staticvec" }

bootloader_api.workspace = true
log.workspace = true
x86_64.workspace = true
linkme.workspace = true
itertools.workspace = true
uart_16550.workspace = true

[dependencies.wasabi-kernel]
path = "../wasabi-kernel"
features = ["test", "no-unicode-log"]
