[package]
name = "testing-derive"
version.workspace = true
edition.workspace = true


[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
paste.workspace = true

[lib]
proc-macro = true
