[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[features]
default = ["color"]
color = ["colored"]
alloc = ["shared/alloc"]


[dependencies]
log.workspace = true
shared = { path = "../shared" }
staticvec = { path = "../staticvec" }
colored = { path = "../colored", optional = true }
