[package]
name = "wasabi-kernel"
version.workspace = true
edition.workspace = true

[features]
no-color = ["colored/no-color"]
no-unicode-log = []
test = ["dep:testing", "shared/test", "mem-backed-guard-page"]
mem-backed-guard-page = []

default = ["mem-backed-guard-page"]

[dependencies]
shared = { path = "../shared" }
shared-derive = { path = "../shared-derive" }
logger = { path = "../logger", features = ["alloc"] }
staticvec = { path = "../staticvec" }
colored = { path = "../colored" }
interrupt-fn-builder =  { path = "../interrupt-fn-builder" }
testing = { path = "../testing", optional = true }

bit_field.workspace = true
bootloader_api.workspace = true
derive_builder.workspace = true
iced-x86.workspace = true
lazy_static.workspace = true
linked_list_allocator = { version = "0.10.5", default-features = false }
linkme.workspace = true
log.workspace = true
noto-sans-mono-bitmap.workspace = true
paste.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
uart_16550.workspace = true
volatile = "0.4.6"
x86_64.workspace = true

[build-dependencies]
walkdir.workspace = true
