[package]
name = "wasabi-kernel"
version = "0.1.0"
edition = "2021"

[features]
no-color = ["colored/no-color"]

[dependencies]
shared = { path = "../shared" }
shared-derive = { path = "../shared-derive" }
logger = { path = "../logger" }
staticvec = { path = "../staticvec" }
colored = { path = "../colored" }

bootloader_api = { version = "0.11.3", path = "../../bootloader/api" }
lazy_static.workspace = true
thiserror.workspace = true
uart_16550 = "0.2.18"
x86_64.workspace = true
log.workspace = true
bit_field.workspace = true
volatile = "0.4.6"
linked_list_allocator = { version = "0.10.5", default-features = false }
paste.workspace = true

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
