[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[features]
alloc = []
test = []
default= ["alloc"]
no-unicode-log = []

[dependencies]
x86_64.workspace = true
log.workspace = true
paste.workspace = true
thiserror.workspace = true
