[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[features]
default= []
no-unicode-log = []

[dependencies]
log.workspace = true
paste.workspace = true
simple_endian.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
x86_64.workspace = true
