[package]
name = "staticvec"
version = "0.1.0"
edition = "2021"

[features]
alloc = []
serde = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }

